#!/usr/bin/bash

# Update the package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        return 200 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart
