#!/usr/bin/env bash

# Update the package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
        add_header Last-Modified $date_gmt;
        if_modified_since exact;
    }

    location = / {
        default_type text/html;
        add_header Content-Type text/html;
        return 200 "Hello World!\n";
        add_header Last-Modified $date_gmt;
        if_modified_since exact;
    }
}

# Restart Nginx
sudo service nginx restart
